### DISCUSSION TITLE
Sharing a USB camera with usbipd in a docker container

### DISCUSSION THREAD

**Discussion by guillaumenibert** [dorssel/usbipd-win#879] [Q&A]
Hello everyone, thank you for your work, I am looking to share my USB camera to a docker container. 
Based on discussion #315, I performed these steps:
 - I recompiled the Linux kernel for WSL with camera driver support,
 - then attached my camera to WSL using usbipd,
 - tested the camera on the Ubuntu default WSL distribution with cheese: it works.
 - `/dev/video0` is visible in the `docker-desktop` distro, but not in the container:

I tried this tip (#315) from @NikLeberg:

> Hi @salvatoreTorsello I use usbipd successfully to forward a USB device to a docker container. For that I had to map `-v /dev:/dev` and add `--privileged` so the container can access the devices. Depending on you device you have to install drivers for it in WSL2 thought.

Adapting it, I tried these configurations (docker compose file), with or without privileges, with or without the *devices* part,

```yml
...
privileged: true
volumes:
   - /dev:/dev
   - /run/desktop/dev:/dev
   - /run/desktop/dev/video0:/dev/video0

devices:
   - /dev:/dev
   - /run/desktop/dev:/dev
   - /dev/video0:/dev/video0
...
```

When I do `lsusb` in my container, the camera is visible, but the output of `ls /dev` does not list `video0`.

I am interested in any advice, whether or not it concerns usbipd or rather WSL/Docker.

Best regards,

Guillaume

--
Docker Desktop for Windows 4.28.0
Usbipd: 4.1.1-dev (from #856)
Host: Windows 11 23H2
Container: Ubuntu 22.04
